language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
script: phpunit
notifications:
    email:
        recipients:
            - mail@filipsedivy.cz
    on_success: change
    on_failure: always