<?php

namespace FS;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-30 at 00:28:31.
 */
class AttactProtectTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AttactProtect
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AttactProtect;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FS\AttactProtect::protect
     * @todo   Implement testProtect().
     */
    public function testProtect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FS\AttactProtect::input
     * @todo   Implement testInput().
     */
    public function testInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
